# Generated by Django 5.2.7 on 2026-01-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestProfile',
        ),
    ]
