# Generated by Django 5.2.7 on 2025-12-28 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0008_alter_layoutitem_i'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=40)),
                ('created', models.DateField(auto_now_add=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_notes', to='grid.grid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StickyNotePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title')),
                ('sticky_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_pages', to='stickynote.stickynote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StickyNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_symbol', models.CharField(choices=[('checkbox_filled', 'checkbox_filled'), ('checkbox_empty', 'checkbox_empty'), ('dash', 'dash'), ('bullet', 'bullet'), ('none', 'none')], default='none', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_lines', to=settings.AUTH_USER_MODEL)),
                ('sticky_note_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_lines', to='stickynote.stickynotepage')),
            ],
        ),
    ]
