# Generated by Django 5.2.7 on 2025-12-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynoteline',
            name='text',
            field=models.CharField(default='blah', max_length=100),
            preserve_default=False,
        ),
    ]
