# Generated by Django 5.2.7 on 2025-12-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNotePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title')),
                ('sticky_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_pages', to='stickynote.stickynote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
