# Generated by Django 5.2.7 on 2025-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynote', '0002_stickynoteline_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynoteline',
            name='line_symbol',
            field=models.CharField(choices=[('checkbox_filled', 'checkbox_filled'), ('checkbox_empty', 'checkbox_empty'), ('dash', 'dash'), ('bullet', 'bullet'), ('none', 'none')], default='dash', max_length=32),
        ),
        migrations.AlterField(
            model_name='stickynoteline',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
