# Generated by Django 5.2.7 on 2025-11-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
        ('projects', '0003_rename_projectfolder_project_folder_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='projects.project'),
        ),
    ]
