# Generated by Django 5.2.7 on 2025-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_alter_grid_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
