# Generated by Django 5.2.7 on 2025-11-19 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_grid_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('static', models.BooleanField(default=False)),
                ('isResizeable', models.BooleanField(default=False)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_items', to='grid.grid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
