# Generated by Django 5.2.7 on 2025-11-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_layoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutitem',
            name='i',
            field=models.CharField(max_length=20),
        ),
    ]
