# Generated by Django 5.2.7 on 2025-11-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_griditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutitem',
            name='type',
            field=models.CharField(default='timer', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GridItem',
        ),
    ]
