# Generated by Django 5.2.7 on 2025-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_layoutitem_type_delete_griditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutitem',
            name='i',
            field=models.CharField(max_length=40),
        ),
    ]
