# Generated by Django 5.2.7 on 2025-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
