# Generated by Django 5.2.7 on 2025-12-08 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0008_alter_layoutitem_i'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=40)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='grid.grid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackObjTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaspedSeconds', models.IntegerField(default=0)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_obj_timer', to='grid.grid')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_obj_timer', to='tracker.tracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_obj_timer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
