# Generated by Django 5.2.7 on 2025-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobjtimer',
            name='timerI',
            field=models.CharField(default='i-test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackobjtimer',
            name='trackerI',
            field=models.CharField(default='i-test', max_length=25),
            preserve_default=False,
        ),
    ]
