# Generated by Django 5.2.7 on 2025-12-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackobjtimer_timeri_trackobjtimer_trackeri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackobjtimer',
            name='timerI',
        ),
        migrations.AddField(
            model_name='trackobjtimer',
            name='gridItemI',
            field=models.CharField(default='test-1', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackobjtimer',
            name='trackerI',
            field=models.CharField(max_length=45),
        ),
    ]
