# Generated by Django 5.2.7 on 2025-12-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
        ('tracker', '0003_remove_trackobjtimer_timeri_trackobjtimer_griditemi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobjtimer',
            name='timer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track_obj_timer', to='timers.timers'),
            preserve_default=False,
        ),
    ]
