# Generated by Django 5.2.7 on 2025-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trackobjtimer_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobjtimer',
            name='customName',
            field=models.CharField(default='timer', max_length=20),
        ),
    ]
