# Generated by Django 5.2.7 on 2025-12-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_trackobjtimer_customname'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackobjtimer',
            name='timespentSeconds',
            field=models.IntegerField(default=0),
        ),
    ]
