# Generated by Django 5.2.7 on 2026-01-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0008_alter_layoutitem_i'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_directories', to='grid.grid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_directories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('note_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_folders', to='note_navigator.notedirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=25)),
                ('raw_text', models.CharField(max_length=300)),
                ('note_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='note_navigator.notefolder')),
            ],
        ),
    ]
