# Generated by Django 5.2.7 on 2026-01-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_navigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='raw_text',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
    ]
