# Generated by Django 5.2.7 on 2026-01-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_navigator', '0002_alter_note_raw_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='raw_text',
        ),
        migrations.CreateModel(
            name='RawObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNum', models.IntegerField()),
                ('text', models.CharField(max_length=80)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_objects', to='note_navigator.note')),
            ],
        ),
    ]
