# Generated by Django 5.2.7 on 2026-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_navigator', '0003_remove_note_raw_text_rawobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawobject',
            name='text',
            field=models.CharField(blank=True, max_length=76),
        ),
    ]
