# Generated by Django 5.2.7 on 2026-01-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_navigator', '0004_alter_rawobject_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawobject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raw_objects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
