# Generated by Django 5.2.7 on 2026-01-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_navigator', '0005_rawobject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawobject',
            name='text',
            field=models.CharField(blank=True, default='', max_length=76),
        ),
    ]
