# Generated by Django 5.2.7 on 2025-11-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0005_alter_layoutitem_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grid.grid')),
            ],
        ),
    ]
