# Generated by Django 5.2.7 on 2025-11-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_griditem'),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='grid.grid'),
        ),
    ]
