# Generated by Django 5.2.7 on 2025-11-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_timer_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='i',
            field=models.CharField(max_length=40),
        ),
    ]
