# Generated by Django 5.2.7 on 2025-12-30 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0008_alter_layoutitem_i'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled table', max_length=20)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='grid.grid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
