# Generated by Django 5.2.7 on 2025-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='i',
            field=models.CharField(default='error', max_length=40),
        ),
    ]
