# Generated by Django 5.2.7 on 2025-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='i',
            field=models.CharField(max_length=40),
        ),
    ]
