# Generated by Django 5.2.7 on 2025-12-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_table_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='table.table')),
            ],
        ),
    ]
