# Generated by Django 5.2.7 on 2025-12-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
