# Generated by Django 5.2.7 on 2025-12-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_rename_table_cell_table_column_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='table.column'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='rows',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='table.row'),
            preserve_default=False,
        ),
    ]
