# Generated by Django 5.2.7 on 2025-12-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_cell_column_cell_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='columnIndex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='rowIndex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
