# Generated by Django 5.2.7 on 2025-12-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_column_user_row_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='rows',
            new_name='row',
        ),
    ]
