# Generated by Django 5.2.7 on 2025-12-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_cell_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
